import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { geistMono, geistSans } from "../utils/fonts";
import CustomNavbar from "../components/Navbar";
import { vazirmatnFont } from "../fonts/font";
import Footer from "../components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html  lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${vazirmatnFont.className} antialiased dark`}>
        <NextUIProvider>
          <CustomNavbar />
          { children }
          <Footer />
        </NextUIProvider>
      </body>
    </html> 
  );
}
