import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { geistMono, geistSans } from "../utils/fonts";
import CustomNavbar from "../components/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}>
        <NextUIProvider>
          <CustomNavbar />
          { children }
        </NextUIProvider>
      </body>
    </html> 
  );
}
